### ISSUE TITLE
Repeated ouputs

### ISSUE THREAD

**Issue by Paul-Reed** [DeanCording/node-red-contrib-persist#1]
After I do a full deploy, I get 2 msg objects in the debug node in quick succession.
I was expecting just to get one message, to replay the stored data.

![dean](https://user-images.githubusercontent.com/973580/34745622-0909045e-f589-11e7-92c8-e477903ef2f1.PNG)

**Comment by DeanCording** [comment]
Thanks Paul,

It's actually worse than that.  Every subsequent deploy adds another message to the output.

Looking at it now.

Dean

**Comment by DeanCording** [comment]
My bad, forgot to remove the node-start event listener on each deploy resulting in a new listener being added on each deploy.

Fixed and new version published on npm.

**Comment by Paul-Reed** [comment]
Sorted now, thanks.

Paul
