### ISSUE TITLE
no such file or directory

### ISSUE THREAD

**Issue by GravityRZ** [DeanCording/node-red-contrib-persist#5]
i get this error

"persistance.json: ENOENT: no such file or directory, open 'persistance.json'"

should be simple
i choose a file called persistance.json but persist in/out can not find it

ehere should this file be?
is it not created when you add it in the node?

strange

**Comment by MDAR** [comment]
Yeah, I can see this issue too.

Did you find a solution to this?

I assumed that the Node would create the json file, do we have to create it somewhere?

**Comment by MDAR** [comment]
UPDATE

It looks like this question has been answered in this Issue

https://github.com/DeanCording/node-red-contrib-persist/issues/2

**Comment by GravityRZ** [comment]
i stopped using it. whenever responses are slow to none it means not a lot of other people have the issue or don't care.

i am now saving my variables as a flow. way easier and also easier to do checks on the status.
