### ISSUE TITLE
How to delete persist-store?

### ISSUE THREAD

**Issue by Schwenkner** [DeanCording/node-red-contrib-persist#8]
The persist-store node is hidden.
I have played with "persist" a bit and decided to not use it, since it doesn't meet my needs.
Then I deleted the file I have assigned for the store.
Now I get always an error, the file does not exist, I have no persist-in/out nodes in my flows.
An export of all flows shows me, the persist-store node is still in and when I try to uninstall with the manager, it tells me it is still in use.

How can I remove this node, otherwise I have to have the files still there.

**Comment by StephanStS** [comment]
Hello @Schwenkner,
did you also delete the persist configuration node?

Step 1: Open configuration nodes:
![image](https://user-images.githubusercontent.com/57687516/85213182-3329e180-b35b-11ea-8a62-bd3e69d13f1f.png)

Step 2: Select persist configuration node and delete via &lt;delete&gt; key:
![image](https://user-images.githubusercontent.com/57687516/85213197-62d8e980-b35b-11ea-96c1-9962c7acfe0f.png)

Step 3: Deploy.

**Comment by Schwenkner** [comment]
Thx, didn't know that (just a beginner).
I have fixed it meanwhile by exporting the whole flows, deleting the node manually and restart.

**Comment by StephanStS** [comment]
@Schwenkner: Would you please close this issue, if it is finished for you?
